Check for Basemap.java version bump in CI

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -28,3 +28,13 @@ jobs:
     - name: Ensure code formatted with mvn spotless:apply
       working-directory: tiles
       run: mvn spotless:check
+    - name: Check for required version bump
+        run: |
+          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}...HEAD)
+          echo "$CHANGED_FILES"
+          TILES_SRC_CHANGED=$(echo "$CHANGED_FILES" | grep '^tiles/src/main' || true)
+          VERSION_CHANGED=$(echo "$CHANGED_FILES" | grep '^tiles/src/main/java/com/protomaps/basemap/Basemap.java$' || true)
+          if [[ -n "$TILES_SRC_CHANGED" && -z "$VERSION_CHANGED" ]]; then
+            echo "::error ::You modified files in tiles/src/main, but did not update Basemap.java."
+            exit 1
+          fi
